### ISSUE TITLE
Particles while warmup & configurable "/warp list" output

### ISSUE THREAD

**Issue by Ghostlyr** [MyWarp/MyWarp#147]
I would like to see the effect of particles on the whole warmup time and more configurable warp list output message's through locale files.

Also make messages in the minecraft-JSON format so that when you click on the list message, it called some command (information about the point or teleportation to it for example).

**Comment by TheE** [comment]
> I would like to see the effect of particles on the whole warmup time...

Interesting idea, will look into it.

> ...and more configurable warp list output message's through locale files.

What exactly do you have in mind? Should the listing include more (or other) details about the listed warps?

Configuration of the listed details would not be done via the locale files, but by using placeholders inside a configuration file. Technically this could be done be extending the current warp-placeholders (used e.g. in welcome messages), but for now I do not see a use-case that justifies the work to do so.

> Also make messages in the minecraft-JSON format so that when you click on the list message, it called some command (information about the point or teleportation to it for example)

Sadly this is impossible within the current Bukkit API. It is planed for the Sponge version though.

**Comment by TheE** [comment]
I tested playing the particle effect during the whole warmup time. Sadly, it does not look very good:
* If the player does not move, the smoke is nearly invisible because it the player stands directly within it.
* If the player moves, it looks strange because the smoke particles cannot follow the moving player due to limitations within Bukkit. The smoke has no longer a visible connection to the player.

Due to this I have decided to not implement particle effects for the warmup time, at least unless it becomes possible to have them follow a player.
