### ISSUE TITLE
PaperSpigot #1113 breaks MyWarp

### ISSUE THREAD

**Issue by vilgrar** [MyWarp/MyWarp#150]
Hi,

PaperSpigot build #1113 (and newer) doesn't work with MyWarp (b169). Prior PaperSpigot 1.12 versions, ranging from #1105 - #1112 will load without problems.

https://pastebin.com/zUUzkZPt

Another plugin also had problems starting from #1113 (but not before). I'm not sure if it's related, but this URL helped him solve it: https://github.com/Ste3et/FurnitureLib/issues/27#issuecomment-307868622

**Comment by TheE** [comment]
Looks like an error within [slf4bukkit](http://rjenkinsjr.github.io/slf4bukkit/), a library MyWarp uses for logging. Its `[ColorMapper](https://github.com/rjenkinsjr/slf4bukkit/blob/master/src/main/java/info/ronjenkins/slf4bukkit/ColorMapper.java#L22)` class relies on `org.fusesource.jansi`, a library that is typically bundled by CraftBukkit (and Spigot). I assume that PaperSpigot no longer bundles this library which results in the reported problem.

Since this is a problem within slf4bukkit I cannot easily fix this myself. I will however report this problem to slf4bukkit and try to get it fixed.

**Comment by TheE** [comment]
I (hopefully) fixed it myself. Please give the latest devBuild a try.
