### ISSUE TITLE
Custom locale translations not working?

### ISSUE THREAD

**Issue by DutchUser** [MyWarp/MyWarp#158]
Hello. Because most of the message are outdated and because i wanna start with a fresh file i searched for a default localizations. But i did not found any and only found 2 broken links.

https://github.com/MyWarp/MyWarp/wiki/Localizations

from here and here into 

Both "here" are broken. And would not work.

404 “This is not the web page you are looking for”

**Comment by TheE** [comment]
Thanks, I updated both links:
> The easiest way to manually start with a new translation is to copy the English files bundled by MyWarp, and translate the content. To do so, copy all files ending with `_en` from [here](https://github.com/MyWarp/MyWarp/tree/master/mywarp-core/src/main/resources/io/github/mywarp/mywarp/lang) and [here](https://github.com/MyWarp/MyWarp/tree/master/mywarp-bukkit/src/main/resources/io/github/mywarp/mywarp/lang) into the inner `lang` folder.

**Comment by DutchUser** [comment]
Hello.

I searched a freash because i though i maked mistike and i was to lazy to check every message. (and other reasons)

But i changed one message to check if it was because a mistake. And i found out that he still dont load or use the changed message. 

warp-warmup.started=§f[§2Warps§f] §aJe zall over 5 seconden geteleporteerd worden naar  ''§f{0}a'' §7Niet bewegen.

Did i do something wrong? Please know that we still have the non-1.12 because our server is not yet 1.12 because of reasons. We have version MyWarp v3.0-beta-4+jenkins-b160.git-1081039991

**Comment by TheE** [comment]
Have you tried if they are working without the `§`, e.g. by just changing the message? What program did you use to edit the files?

**Comment by TheE** [comment]
I just tested it, for me everything works fine, including coloring with `§` (although I would not recommend using them because I cannot guarantee that they will continue to work).

If you still have issues, please make sure to only edit the files with a proper text editor (e.g. Notepad++ on Windows or TextEdit in Plain Text Mode on macOS).

**Comment by DutchUser** [comment]
Can you please say with what for version you tested it. Because i forget this topic i just saw it. And re-tested myself. It is not because it starts with the §. Al other changed message starts with § and they work fine whitout any issue, 

Its just the cooldown and delay message's that he ignore. (the plugin.)

I also tested with starting and ending ' '

**File:** https://pastebin.com/aSsGm5kp
**Version:** MyWarp v3.0-SNAPSHOT+jenkins-b175.git-134a99586f

**Comment by TheE** [comment]
Messages for warmups and cooldowns were recently moved into their own file, which is why your version is not working.

Just download [this file](https://github.com/MyWarp/MyWarp/blob/master/mywarp-core/src/main/resources/io/github/mywarp/mywarp/lang/Timers.properties) (by clicking on Raw), rename it to `Timers_nl_NL.properties` (as you did with the other files) translate the strings and move it into the `[MYWARP-PLUGIN-FOLDER]/lang/io/github/mywarp/mywarp/lang/`.
