### ISSUE TITLE
Database and new server hosting

### ISSUE THREAD

**Issue by MineServidorCraft** [MyWarp/MyWarp#164]
I change my server hosting and when a start the server i have this error on console:
(In game nothing ocurred)

https://pastebin.com/R6ERuk82

**Comment by TheE** [comment]
It seems like the process running the server cannot create the database file or one of the folders that make up the path to the database file. Please check if `storage.url` is correct in the `config.yml` and if the server process has read and write access to this directory.

This problem is caused by an error with the error code `90062` in the H2 database engine, see [here](https://www.h2database.com/javadoc/org/h2/api/ErrorCode.html#c90062) for more information.

**Comment by MineServidorCraft** [comment]
I see that url isn't the same. I need to ask for my last server hosting and give this files?

http://i.imgur.com/27J5InO.png

**Comment by TheE** [comment]
MyWarp stores all files in a database. If you use H2, the database is located within a file named `warps.h2.db` which is normally created an MyWarp's plugin directory.

If you start with a new file, as you had when changing the URL, obviously all warps are inaccessible because your are using a different database.

Therefore you must make sure that you take the `warps.h2.db` file from your old folder and upload it into MyWarp's plugin directory on the new server. Than simply remove the line `storage.url` line from your configuration file so that MyWarp will regenerate it using the default path.
