### ISSUE TITLE
Warp give issue's

### ISSUE THREAD

**Issue by DutchUser** [MyWarp/MyWarp#179]
How does the /warp give commands works? They are mostly broken i cannot find any information how it works.

**Comment by TheE** [comment]
Is there anything in the official documentation that does not work or gives errors?

>`/warp give [-df] <player> <name>`
>
>Gives the warp of the given name to the player of the given name, if he accepts it.
>Use [-f] to ignore any warp-limits of the receiving player.
>Use [-d] to give the warp directly without asking for acceptation first.

**Comment by DutchUser** [comment]
Its more. How can he accept or decline it. And i edited the "warp-acceptance-conversation.want-to-accept = " message. But he still get the defaault english >> https://pastebin.com/3e138zB0

**Comment by DutchUser** [comment]
And also an other one is bugged as hell. When i want to give an warp to myself its just say this in the chat: (lightred)give.is-owner

And in the file that line is >https://pastebin.com/3bn1pHDD 
I also tried "{0}" but still the same issue.

**Comment by TheE** [comment]
The `give.is-owner` error should be fixed as of the latest devBuild.

Regarding the acceptance conversation: Your translation key is wrong, the correct one is: `warp-acceptance.want-to-accept`. See [this file](https://github.com/MyWarp/MyWarp/blob/master/mywarp-bukkit/src/main/resources/io/github/mywarp/mywarp/lang/Conversations.properties) for further reference.

As a side node: I think that MyWarp's Dutch translation is [relatively complete](https://crowdin.com/project/mywarp/nl#), maybe you can use (and expand) it instead of relying on your own files?
