### ISSUE TITLE
MySQL database: welcome messages with RU characters are become "?"

### ISSUE THREAD

**Issue by ArtNRG** [MyWarp/MyWarp#185]
### Description of the Problem
I typing /warp welcome any_warp.
The welcome message I typed looks like "Добро пожаловать на /warp any_warp"
The welcome message in MySQL database looks like "????? ?????????? ?? /warp any_warp"
So after server restart or /mywarp reload the welcome message become "????? ?????????? ?? /warp any_warp" in game.
### Steps to Reproduce
1. Setup mywarp to use MySQL database.
2. Create any warp
3. Set welcome message "проверка" or any RU text.
4. Type "/mywarp reload" or restart the server
5. Use that warp and see all RU characters inside the welcome message become "?" characters.

### Affected Version
* MyWarp: 3.0-SNAPSHOT+jenkins-b192.git-91cdc14a6b
* Minecraft and Bukkit Implementation: git-Paper-1469 (MC: 1.12.2)

**Comment by TheE** [comment]
Will look into it, may be a encoding error on the database side.

**Comment by TheE** [comment]
Should be fixed in the latest devBuild.

Until now, MyWarp did not specify which collation to use for certain text-fields in the MySQL database, including the field which stores welcome-messages. Instead, the MySQL-server's default collation was used. This behaviour could cause the problems you described if the MySQL-sever's default collation is not able to properly handle some strings.

From now on, every text is stores in (the true) UTF-8, hopefully eliminating such problems.
