### ISSUE TITLE
[Request] Few things, More options for /warp limits, locale fixes. And a improved /warp welcome

### ISSUE THREAD

**Issue by DutchUser** [MyWarp/MyWarp#191]
### 1. Option to change the (x/x): (fix for the 1 space between "warps (x/x)")

This is because i want to use the : after as example "Private warps(x/x):". And the ( / ) because we wanty to use more then 1 color in the (x/x).
(ps) Yes i know. I can still do that. But then get as example "Private warps: (0/3):" and we dont want that.

### 2. Add the only players with an x permission can see the worlds part in /warp limits. 

This because we don't want that players can see all world names. 

### 3. Fix that the locales are missing lines, it seem to miss some lines.

It is missing the .**/warp give** lines, and the **/warp welcome** 

### 4. Change how /warp welcome works. See down below an example.

1. player typed the command /warp welcome <warp> 
2. And then need to type what he want. And if he want to cancel it. He need to use #cancel or something. 

Because currently you have 30 seconds. And that's a bit annoying.

**Comment by TheE** [comment]
Sorry for not replying earlier, I do not have much time for MyWarp at the moment.

> 1. Option to change the (x/x): (fix for the 1 space between "warps (x/x)")

Done. I have changed the translation of all headings in the `warp assets` command to include the numbers. This way you can configure how the numbers are displayed in your translation.

> 2. Add the only players with an x permission can see the worlds part in /warp limits.

For now I am not going to implement this because it further complicates the already complicated code of the `/warp assets` command. Also, the command is intended to display both, existing warps and all applicable limits which is useful when setting up limits across multiple worlds. If I introduce further options setting up limits will just become even more complicated.

However, you can now remove the worlds completely from the translated message if you wish by removing the `{0}` from the message below:
```PROPERTIES
assets.total=Warps in {0} ({1,number,integer}/{2,number,integer}):
```

> 3. Fix that the locales are missing lines, it seem to miss some lines.

The lines for both commands are split between [`Comands.properties`](https://github.com/MyWarp/MyWarp/blob/master/mywarp-core/src/main/resources/io/github/mywarp/mywarp/lang/Commands.properties) and [`Conversations.properties`](https://github.com/MyWarp/MyWarp/blob/master/mywarp-bukkit/src/main/resources/io/github/mywarp/mywarp/lang/Conversations.properties).

> 4. Change how /warp welcome works. See down below an example.

On Bukkit there always is a maximum duration (5 minutes by default). I understand that 30 seconds is somewhat short. Therefore, as of the latest commit, you have 60 seconds.
