### ISSUE TITLE
How i can downlaod translation from crowdin?

### ISSUE THREAD

**Issue by SHADOWDANCH** [MyWarp/MyWarp#197]
### Question
How i can get russian translation from crowdin? Download button inactive. Or how else i can download translation?

**Comment by TheE** [comment]
It seems that, unfortunately, only project administrators can download the files from crowdin. Therefore I have downloaded the Russian translation files, you can finder them in the attached archive.

However, please note that all builds of Mywarp include these translations, there is no need to manually download these translations in order to use them.

[mywarp_russian-translations_2019-01-09.zip](https://github.com/MyWarp/MyWarp/files/2742752/mywarp_russian-translations_2019-01-09.zip)

**Comment by SHADOWDANCH** [comment]
It's english translation. And in build from bukkit.org and project site included only english translations.
