### ISSUE TITLE
Can't find offline players

### ISSUE THREAD

**Issue by martijnpu** [MyWarp/MyWarp#204]
### Description of the Problem
'/warp list -c <player>' displays no offline players
You can't either invite offline players to your warps.
![image](https://user-images.githubusercontent.com/38832167/51684950-8a544700-1fed-11e9-9e7c-1d7b4375f747.png)

### Steps to Reproduce
- Player creates a warp
- Player goes offline
- Player2 executes /warp list -c Player
- Result: No matches found!

### Log Output
```
none
```

### Affected Version
* MyWarp: ` 3.0+travis-b1749.get-c3cbe614dd `
* Minecraft and Bukkit Implementation: `spigot 1.13.2-R0.1-SNAPSHOT`
### Additional context
This is a very annoying bug

**Comment by TheE** [comment]
I cannot reproduce this behaviour: Warps of offline players are correctly displayed and I can also invite offline players without any problems. Is your server in online mode? Can the server connect to Mojang's API to resolve player names to UUIDs?

**Comment by martijnpu** [comment]
Hmm, we are an offline server. Maybe that's part of the problem. But I hope
there is a fix for this.

Op do 24 jan. 2019 23:36 schreef TheE <notifications@github.com:

**Comment by TheE** [comment]
Sorry, I fear that this cannot be resolved for technical reasons.

MyWarp only stores warp-creators, invited players etc. as UUIDs in order to support name changes. When you use `/warp list -c player-name`, MyWarp has to convert `player-name` into a UUID:

1. If any of the online players matches `player-name`, the UUID of this player is used.
2. If there is no match, Mojang's servers are queried to convert the name into a UUID.

This works fine if your server is in online mode. However, if your server is on offline mode, these UUIDs differ: Mojang uses its own UUID (and does not return any UUID for players who have not bought the game), while the server returns the hashed username.
