### ISSUE TITLE
insufficient permission

### ISSUE THREAD

**Issue by Friky1** [MyWarp/MyWarp#217]
I want default players to be able to use the basic warp commands, and I've tried using vault with group manager. I even edited the permissions but nothing works. OP's can use it, but whenever anyone else tries to it just says "insufficient permission".

**Comment by Nykoload** [comment]
Currently looking into this myself, looks like an alternate plugin is needed to fix it and grant default permissions. Either VaultAPI or an alternative. I'll post again if I can find anything solid which works and how I got it set up.

**Comment by Nykoload** [comment]
Figured it out. You need to set default users permission to use mywarp commands. It's as easy as typing `/[perm] group default permission set mywarp.cmd.* true`  with a permissions plugin installed. Myself, I used Luckperms, the format for that plugin is `/lp group default permission set mywarp.cmd.* true`. This will give the default user access to all commands that warp uses, you can select each one if you would prefer, just refer to this page: https://github.com/MyWarp/MyWarp/wiki/Permission-Reference

You can find luckperms .jar here: https://luckperms.github.io/
Just installed to your plugins/mods folder and restart server. Hope this helps.

**Comment by TheE** [comment]
Without an external permission plugin, MyWarp only grants permissions for command usage to OPs. While Bukkit allows to grant regular users permissions by default, this caused some problems for administrators in the past; therefore, we only grant permissions to OPs by default.

You will need to use a permissions plugin and configure it so that your users have the permission to the commands they should have access to accordion to the documentation of your permissions plugin.

For GroupManager, this process is described [here](http://wiki.ess3.net/wiki/Group_Manager/Config). A list of MyWarp's permission can be found [here](https://github.com/MyWarp/MyWarp/wiki/Permission-Reference#command-permissions) (normally you might want to grant access to usage, management, informative, social and utility commands).
