### ISSUE TITLE
/warp private fails

### ISSUE THREAD

**Issue by Beaupedia** [MyWarp/MyWarp#222]
When attempting to privatize a warp, example our warp named "Games", we receive the message

"Could not find a player named 'e09505b5-0449-4d0b-986d-5f1d44886003'. Is she online?" That UUID belongs to the person who created the warp. We've been using MyWarp for many years, this is certainly new with our recent upgrade to 1.14.4.

Server: Spigot 1.14.4
MyWarp: mywarp-bukkit-3.0.2-SNAPSHOT-all

**Comment by TheE** [comment]
This should only happen if the owner of the warp that you attempt to privatize is offline. If you have warp limits enabled, MyWarp attempts to check the owner's limits before privatizing or publicizing a warp. This involves checking the owner's permissions with, on Bukkit, can only be done for players who are online.

You can overwrite the limit check using the `-f` switch like so: `warp privatize -f <warp-name>`.

By the way, this is not related to the display of the owner's UUID. This only means that MyWarp does not know the display name of this player, likely because the player did not login for a long time.

**Comment by Beaupedia** [comment]
Interesting, thank you. I went ahead and disabled limits entirely, didn't realize they were even there. Apologies for the false report and thank you so very much for continuing to maintain this great plugin.
