### ISSUE TITLE
Pressure plates, levers (anything that can activate redstone) when activating warp sign does not also activate redstone [Bug]

### ISSUE THREAD

**Issue by tatem8** [MyWarp/MyWarp#224]
### Description of the Problem
When using a warp sign via anything that can power redstone will completely ignore any redstone.
I'm not sure if this was intentional or not, it very well could be intentional, but I would love to have the option to enable or disable this feature if it was intended. If it is intentional I can move this post to the feature request category :)

### Steps to Reproduce
place a pressure plate, button, etc linked with redstone and a warp sign and the input will ignore redstone

### Affected Version
* MyWarp: ` <mywarp-bukkit-3.1.1-SNAPSHOT-all> `
* Minecraft and Bukkit Implementation: `<Spigot Minecraft 1.14.4> `

**Comment by TheE** [comment]
For reference, this behaviour was introduced by 1b75d823cdab759f84d1f1c0dd4ade7d34132084.

**Comment by TheE** [comment]
This behaviour was added in order to fix 'Player moved wrongly!' messages that occurred when  using warp signs. Upon testing, removing this behaviour does not lead to such messages, so it may no longer be needed. However, if the problem occurs again, I may have to add it again.

Anyway, could you test if the latest development build fixes the issue without re-intoducing  'Player moved wrongly!' messages?

**Comment by tatem8** [comment]
Hello! That was super fast, and it works flawlessly. Redstone is activated and there are no 'Player moved wrongly' errors in the console or logs.
Thank you so much, i really appreciate your work
