### ISSUE TITLE
Command blocks do not trigger when warping out of loaded chunks via pressure plate [Bug]

### ISSUE THREAD

**Issue by tatem8** [MyWarp/MyWarp#232]
### Description of the Problem
When warping to a warp outside of the loaded chunks via pressure plate, command blocks also powered by the same plate will not trigger. However when you go back into those loaded chunks the command blocks will update and trigger.

### Steps to Reproduce
set a warp and go very far away. set a pressure plate to that warp and also set a command block with a simple command that says hello in chat or something like that. When you use the plate it will not trigger. if you go back to the chunks with the command block in them afterwards it will update and trigger

### Affected Version
* MyWarp: ` 3.1.1-snapshot-all `
* Minecraft and Bukkit Implementation: `Spigot 1.14.4 `

**Comment by tatem8** [comment]
found solution - increasing moved-too-quickly-multiplier in spigot.yml enabled command blocks to be triggered from a far distance

**Comment by TheE** [comment]
This only happens when using pressure plates and not when using buttons or levers, right?

I guess that technically the problem is very much the same as #223. Somehow, teleporting players from plates interfere with their movement and Vanilla's anti-cheat checks, which leads to strange results. If so, there is unfortunately nothing I can do to fix the issue, although future versions of Spigot or MC might fix it.

I am going to add a note about this to the documentation.

**Comment by TheE** [comment]
[Done](https://github.com/MyWarp/MyWarp/wiki/Warp-Signs#physical-warp-signs).
