### ISSUE TITLE
Help with permissions

### ISSUE THREAD

**Issue by nutellap** [MyWarp/MyWarp#340]
I'm not very good with the technical stuff so I'm really struggling to figure out how to change the permissions so that non op players can use warp signs. I have the LuckPerms plugin and its a Bukkit server. I would really appreciate some clear instructions on how to change the permissions because I don't understand how to use the commands given on [here](https://github.com/MyWarp/MyWarp/wiki/Permission-Reference). Thank you in advance

**Comment by tjzetty** [comment]
I am also having the same problem. Only op players can use warps on my bukkit server.

**Comment by nutellap** [comment]
I figured it out! Since I have **LuckPerms** I was able to get rid of all of a players permissions and then give them permissions to use MyWarp. I don't know how it works with other perm plugins but I simple do:
_/lp user [username] permission set * false_
_/lp user [username] permission set mywarp.* true_
In the first command, the _*_ means all permissions and in the second command, the _mywarp.*_ means all of the mywarp commands. If you don't already have **LuckPerms** I would recommend it! I hope this helped :)

**Comment by tjzetty** [comment]
Where did you download the LuckPerms pugin? I couldn't find it on dev.bukkit

**Comment by TheE** [comment]
Hi. I belief there is some confusion on how permissions work on Bukkit/Spigot.

To use MyWarp's commands, players need to have the corresponding permission. If you install MyWarp **without any additional configuration**, your players will **not** be able to do anything because they lack these permissions, except for players who are OP (via Minecraft's `/op <player>`) who have permissions to use all of MyWarp's commands.

What you want to do is grant your regular (non-OP) players to use (some) commands. This is done via a permissions plugin such as LuckyPerms, PermissionsEx, bPermissions... How you grant the permissions depends on the permissions plugin, so you need to check the documentation of your permissions plugin.

You may find a list of commands, together with the required permission, [here](https://github.com/MyWarp/MyWarp/wiki/Command-Reference).

To make things easier to configure, there are a couple of 'bags' available that bundle the permissions of several commands together. For instance, if want to give your players permissions to use all of MyWarp's commands, you may grant them the `mywarp.cmd.*` permission. A list of all permissions, including such 'bags', is available [here](https://github.com/MyWarp/MyWarp/wiki/Permission-Reference).

Feel free to reopen the ticket if you have additional questions. 😃

**Comment by nutellap** [comment]
https://luckperms.net/download you can find the download link here :)
