### ISSUE TITLE
plugin crashes in 1.17.1 when tab complete activates

### ISSUE THREAD

**Issue by HammerWizrd** [MyWarp/MyWarp#366]
so im using this plugin on a 1.17.1 paper server and when i upgraded from 1.17 the plugin crashes itself whenever you try use a command with it, ill get as far as /warp and the moment i hit space itll crash. i dont quite know how to get ahold of you other than here so if you see this my discord tag is Hammer_Wizrd#8475.

Here is also a copy from the server cmd of the issue and its issues on boot with 1.17.1 : https://mcpaste.io/b57082f1f5038c71

**Comment by HammerWizrd** [comment]
updated to 353 and the issue still persists
https://mcpaste.io/a119e1768750d7fd

**Comment by TheE** [comment]
After some research, it appears that the error may be caused by a corrupted JAR-file. This happen if you replace a plugin's JAR-file while the server is still running, or if you are using `/reload`.

Please try the following:
- Stop your server
- Delete MyWarp's plugin-file (`mywarp-bukkit-3.1.1-all.jar`)
- Download a fresh copy from [BukkitDev](https://dev.bukkit.org/projects/mywarp/files) and drop it in your plugin folder
- Start the server

In the last log I also noticed that there appears to be some issue with MyWarp's H2 database:
````
29.10 20:16:16 [Server] ERROR [MyWarp] Failed to initialize warp storage.
29.10 20:16:16 [Server] ERROR [MyWarp] (Message 90062 not found) [90062-200]
````
The error indicates that [H2 cannot create its database file](http://www.h2database.com/javadoc/org/h2/api/ErrorCode.html#c90062). This may or may not be related to the problem above. Are you using the storage default configuration?

**Comment by HammerWizrd** [comment]
so we got the issue sorted out, turns out it was a combo of corrupted .jar file, lost database file, and an initial setup after an FTP transfer. one of the assistants found that the plugin wasnt able to find the previous database file bc the location was swapped during the transfer and wasnt renamed causing the autocomplete to break. a rename and it was all good to go! Thank you again for the help!
