### ISSUE TITLE
Add warps without creators

### ISSUE THREAD

**Issue by TheExceed** [MyWarp/MyWarp#87]
Warps that are shown above regular warps in the warp list.

**Comment by TheE** [comment]
Could you elaborate a bit on how these 'admin warps' should behave on the server and how they differ from public or private warps?

**Comment by TheExceed** [comment]
@TheE Basically they are not much different from normal warps however they are basically stickied at the top of the of the warp list for convenience on the players and the information of the creator and what not would not be there. For important warps like tutorials, markets, etc.

**Comment by TheE** [comment]
I think xWarps implemented something similar with 'global warps'.

I am not going to add this feature with MyWarp 3 because it is pretty hard to implement with the current project design. I intend however to make warps and warp-date way more flexible at some point, be handling everything as flags (similar to WorldGuards flags for example, see #73). Once this is done, warps that work as you described will be implemented.
