### ISSUE TITLE
Use API's safety algorithms when running on Sponge

### ISSUE THREAD

**Issue by Ghostlyr** [MyWarp/MyWarp#95]
I am using this plugin on modded server. MyWarp teleport safety feature does not recognize modded blocks under warp point and rejects teleportation.
It would be helpful if has been added mod material-whitelist to configuration.

**Comment by TheE** [comment]
Unfortunately on Bukkit there is no way to properly implement such a whitelist without directly hooking into the Forge mod due to Bukkit's poorly design.

Luckily Sponge somewhat solves this problem because it is designed with mods in mind. The Sponge version will use Sponge's own safety algorithm; mods can hook into this algorithm if they support Sponge and everything just works without any custom whitelist.

I will leave this ticket open as a reminder for myself to implement this in the Sponge version.

**Comment by TheE** [comment]
I am going to close this ticket, as the required abstraction was added to the core in 8e1a186.
